[functions]
  external_node_modules = ["@prisma/client", "@prisma/client-write", "@prisma/client-indexer"]
  included_files = ["node_modules/@prisma/client-write/**", "node_modules/@prisma/client-indexer/**", "node_modules/.prisma/**"]
