[build]
  command = "cd apps/landing && npm ci --legacy-peer-deps && npm run build && rm -rf .next/cache"
  publish = "apps/landing/.next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  included_files = ["node_modules/@prisma/client-write/**", "node_modules/@prisma/client-indexer/**", "node_modules/.prisma/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
